const express = require("express");
const cors = require("cors");
const dotenv = require("dotenv");
dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
const DbConnection = require("./DbConnection");
const port = process.env.PORT || 8001;
const studentrouter = require("./Routes/student-routes");
const leaverrouter = require("./Routes/leave-router");
const teacherRouter = require("./Routes/teacher-routes");
const rectorRouter = require("./Routes/rector-routes");
app.listen(port, () => {
  DbConnection();
  console.log(`Example app listening on port ${port}`);
});
app.use("/student", studentrouter);
app.use("/leave", leaverrouter);
app.use("/teacher", teacherRouter);
app.use("/rector", rectorRouter);
